name = "NRS3UncertaintyCone"
defaultTargets = ["NRS3UncertaintyCone"]

[leanOptions]
autoImplicit = false

[[require]]
name = "NavaRobertsonIndependent"
git = "https://github.com/naype888-cloud/nava-robertson-schrodinger.git"
rev = "354921a62b69cc90b07811cde7c6d038977578c8"

[[lean_lib]]
name = "NRS3UncertaintyCone"
